### ISSUE TITLE
File exists: 'microbit-build'

### ISSUE THREAD

**Issue by carlosperate** [Bottersnike/Micro-Pi#1]
Downloaded and manually installed dependencies, then the steps to reproduce:

* `python -m micropi ` 
* Then a window comes up asking about "enabling quick start"? No idea what that means at this point, so I click "No".
* I don't have my microbit plugged in (just wanted to to checkout the IDE), so when trying to find the microbit directory I cancel that as well.
* Application closes.
* Next time I open the application following exception happens:
```
    Installing Build Enviroment
    Traceback (most recent call last):
      File "micropi/micropi.py", line 1512, in main
      File "micropi/micropi.py", line 312, in setupBEnv
    OSError: [Errno 17] File exists: 'microbit-build'
    None
```

`~/.micropi/microbit-build` directory is left behind. So if this is a scrap directory you could check if it exist first and remove it's contents if it does.

**Comment by Bottersnike** [comment]
Try deleting the .mocropi directory then restart micropi. This time, set a location for the mocrobit (it doesn't matter if it exists) then try. The microbit-build is a temp Dir so it crashed when it tried to recreate it. If that doesn't work I may have either solutions.

**Comment by carlosperate** [comment]
Yeah, that is what I tried (deleting the .micropi folder and setting an empty folder as the microbit location) and it does work, sorry, I should have clarified that.

**Comment by Bottersnike** [comment]
I'll patch that ASAP.

**Comment by Bottersnike** [comment]
Try again now (after git pull). It shouldn't crash.

**Comment by carlosperate** [comment]
Tested the latest master, it's looking good!
Cannot replicate any more because of the rework of the start dialogs to select a microbit and all that, so can definitely close this issue as fixed :)

What does the quick start option do btw?
Also, in case you are interested to know, I've just added the project to the https://github.com/carlosperate/awesome-microbit list :)

**Comment by Bottersnike** [comment]
I've moved quickstart into the settings menu with a default value of on. When it's off, the entire build directory is deleted and recreated. As a result, it is always up to date, but takes a while to start.
